# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Category.create(name:"PIZZA")
# Category.create(name:"GOURMET PIZZAS")
# Category.create(name:"STROMBOLIS")
# Category.create(name:"BURGERS")
# Category.create(name:"HOAGIES")
# Category.create(name:"GRINDERS")
# Category.create(name:"SANDWICHES")
# Category.create(name:"CLUB SANDWICHES")
# Category.create(name:"QUESADILLAS")
# Category.create(name:"STEAKS")
# Category.create(name:"CHICKEN STEAKS")
# Category.create(name:"WRAPS")
# Category.create(name:"BUFFALO WINGS")
# Category.create(name:"BREADED WINGS")
# Category.create(name:"GYROS")
# Category.create(name:"SALADS")
# Category.create(name:"CHICKEN PLATTERS")
# Category.create(name:"SEAFOOD PLATTERS")
# Category.create(name:"PASTA")
# Category.create(name:"SIDE ORDERS")
# Category.create(name:"KIDS MENU")
# Category.create(name:"DESSERTS")
# Category.create(name:"BEVERAGES")
#
# # Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"Plain", description:"Sauce & Cheese",category_id:1,price:"5.99",price2:"8.75",price3:"10.25")
# Item.create(name:"White Spices", description:"Olive Oil, Fresh Garlic, Mozzarella, Oregano",category_id:1,price:"5.99",price2:"8.75",price3:"10.25")
# Item.create(name:"White Ricotta", description:"Olive Oil, Fresh Garlic, Oregano, Ricotta & Mozzarella",category_id:1,price:"6.99",price2:"9.99",price3:"11.25")
# Item.create(name:"Upside Down Pizza", description:"Mozzarella & Provolone Cheese & Sauce on Top",category_id:1,price:"6.25",price2:"8.99",price3:"10.49")
# Item.create(name:"Toppings", description:"per topping",category_id:1,price:"1.25",price2:"2.25",price3:"2.40")
# Item.create(name:"1/2 Topping", description:"per topping",category_id:1,price:".70",price2:"1.15",price3:"1.25")
# Item.create(name:"Extra Sauce", description:"",category_id:1,price:".75",price2:"1.50",price3:"2.00")
# Item.create(name:"Buffalo Chicken", description:"Blue Cheese, Buffalo Hot Sauce, Mozzarella & Grilled Chicken",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"BBQ Chicken", description:"BBQ Sauce, Mozzarella, Grilled Chicken",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Greek Pizza", description:"Spinach, Feta, Tomatoes & Olives",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Veggie Supreme", description:"Mushrooms, Onions, Spinach, Green Peppers, Tomatoes, Extra Cheese",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Garden of Earthly Delights", description:"White Pizza with Spinach, Broccoli & Ricotta",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Four Cheese", description:"Mozzarella, Provolone, Colby, Parmesan",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Hawaiian", description:"Ham, Pineapple & Bacon Bits",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Cheese Steak", description:"Topped with our Cheese-Steak Meat",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Meat Lovers", description:"Pepperoni, Sausage, Bacon & Ham",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Dimi's Special", description:"Mushrooms, Green Peppers, Pepperoni, Onions, Ground Beef, Sausage, Tomatoes & Extra Cheese",category_id:2,price:"9.99",price2:"13.99",price3:"15.99")
# Item.create(name:"Cheese & Sauce", description:"",category_id:3,price:"7.49",price2:"10.99",price3:"")
# Item.create(name:"Steak", description:"",category_id:3,price:"9.25",price2:"13.75",price3:"")
# Item.create(name:"Pepperoni", description:"Beef or Pork",category_id:3,price:"8.99",price2:"12.99",price3:"")
# Item.create(name:"Grilled Chicken", description:"",category_id:3,price:"9.25",price2:"13.75",price3:"")
# Item.create(name:"Chicken Steak", description:"",category_id:3,price:"9.25",price2:"13.75",price3:"")
# Item.create(name:"Buffalo Chicken", description:"Grilled Chicken w/ Hot Sauce, Mozzarella & Blue Cheese",category_id:3,price:"9.75",price2:"14.25",price3:"")
# Item.create(name:"Hot Italian Sausage", description:"",category_id:3,price:"9.25",price2:"13.25",price3:"")
# Item.create(name:"Italian Meats", description:"Cappicola, Genoa, Salami, Ham, Green Peppers & Onions",category_id:3,price:"9.25",price2:"13.25",price3:"")
# Item.create(name:"Meatball", description:"100% Beef",category_id:3,price:"8.99",price2:"12.99",price3:"")
# Item.create(name:"Vegetarian", description:"Mushrooms, Spinach, Green Peppers, Red Onions, Tomatoes & Broccoli",category_id:3,price:"8.99",price2:"12.99",price3:"")
# Item.create(name:"Dimi's Special", description:"Steak, Onions, Mushrooms, Pepperoni, Green Peppers",category_id:3,price:"10.75",price2:"14.75",price3:"")
# Item.create(name:"Hamburger", description:"",category_id:4,price:"4.35",price2:"6.35",price3:"")
# Item.create(name:"Cheeseburger", description:"",category_id:4,price:"4.75",price2:"6.75",price3:"")
# Item.create(name:"Pizza Burger", description:"",category_id:4,price:"4.99",price2:"6.99",price3:"")
# Item.create(name:"Bacon Cheeseburger", description:"",category_id:4,price:"5.99",price2:"7.99",price3:"")
# Item.create(name:"Turkey Cheeseburger", description:"",category_id:4,price:"4.75",price2:"6.75",price3:"")
# Item.create(name:"Turkey & Cheese", description:"",category_id:5,price:"6.99",price2:"11.99",price3:"")
# Item.create(name:"Italian", description:"Cappicola, Genoa, Salami, Ham & Provolone Cheese",category_id:5,price:"6.99",price2:"11.99",price3:"")
# Item.create(name:"Ham & Cheese", description:"",category_id:5,price:"6.75",price2:"10.99",price3:"")
# Item.create(name:"Roast Beef & Cheese", description:"",category_id:5,price:"6.99",price2:"11.99",price3:"")
# Item.create(name:"Corned Beef & Cheese", description:"",category_id:5,price:"6.99",price2:"11.99",price3:"")
# Item.create(name:"Mixed Cheese", description:"American and Provolone",category_id:5,price:"6.50",price2:"10.99",price3:"")
# Item.create(name:"Tuna & Cheese", description:"",category_id:5,price:"6.99",price2:"11.99",price3:"")
# Item.create(name:"Chicken Salad & Cheese", description:"",category_id:5,price:"6.99",price2:"11.99",price3:"")
# Item.create(name:"American/Regular", description:"Cooked Salami, Ham & American Cheese",category_id:5,price:"6.75",price2:"10.99",price3:"")
# Item.create(name:"Kosher", description:"Roast Beef, Corned Beef, Turkey & American Cheese",category_id:5,price:"6.99",price2:"11.99",price3:"")
# Item.create(name:"Flounder", description:"American Cheese, Lettuce, Tomatoes, Onions & Oregano",category_id:6,price:"6.99",price2:"11.99",price3:"")
# Item.create(name:"Meatball", description:"Marinara Sauce & Provolone Cheese",category_id:6,price:"6.75",price2:"11.49",price3:"")
# Item.create(name:"Italian Sausage", description:"Green Peppers, Onions, Marinara Sauce & Provolone Cheese",category_id:6,price:"6.99",price2:"11.99",price3:"")
# Item.create(name:"Chicken Parmesan", description:"Fried or Grilled Chicken with Marinara Sauce & Provolone Cheese",category_id:6,price:"7.40",price2:"11.99",price3:"")
# Item.create(name:"Cheeseburger", description:"",category_id:6,price:"6.99",price2:"10.99",price3:"")
# Item.create(name:"Turkey & Cheese", description:"",category_id:7,price:"5",price2:"",price3:"")
# Item.create(name:"Roast Beef & Cheese", description:"",category_id:7,price:"5.25",price2:"",price3:"")
# Item.create(name:"Ham & Cheese", description:"",category_id:7,price:"4.75",price2:"",price3:"")
# Item.create(name:"Tuna Salad", description:"",category_id:7,price:"5.25",price2:"",price3:"")
# Item.create(name:"Chicken Salad", description:"",category_id:7,price:"5",price2:"",price3:"")
# Item.create(name:"BLT", description:"",category_id:7,price:"4.75",price2:"",price3:"")
# Item.create(name:"Flounder & Cheese", description:"",category_id:7,price:"5.25",price2:"",price3:"")
# Item.create(name:"Corned Beef Special", description:"Russian Dressing, Cole Slaw, Swiss Cheese on Rye",category_id:7,price:"5.75",price2:"",price3:"")
# Item.create(name:"Chicken Sandwich", description:"Fried or Grilled Chicken with Cheese",category_id:7,price:"5",price2:"",price3:"")
# Item.create(name:"Turkey", description:"With Bacon, Lettuce & Tomato",category_id:8,price:"8.25",price2:"",price3:"")
# Item.create(name:"Ham & Cheese", description:"With Lettuce & Tomato",category_id:8,price:"8.25",price2:"",price3:"")
# Item.create(name:"Roast Beef & Cheese", description:"With Lettuce & Tomato",category_id:8,price:"8.25",price2:"",price3:"")
# Item.create(name:"Corned Beef", description:"With Cheese, Lettuce & Tomato",category_id:8,price:"8.25",price2:"",price3:"")
# Item.create(name:"Tuna Salad", description:"With Egg, Cheese, Lettuce & Tomato",category_id:8,price:"8.25",price2:"",price3:"")
# Item.create(name:"Chicken Salad", description:"With Lettuce & Tomato",category_id:8,price:"8.25",price2:"",price3:"")
# Item.create(name:"BLT", description:"Bacon, Lettuce, Tomato",category_id:8,price:"8.25",price2:"",price3:"")
# Item.create(name:"Cheese", description:"With Sauce",category_id:9,price:"5.99",price2:"",price3:"")
# Item.create(name:"Chicken", description:"With Cheese & Sauce",category_id:9,price:"6.49",price2:"",price3:"")
# Item.create(name:"Steak", description:"With Cheese & Sauce",category_id:9,price:"6.99",price2:"",price3:"")
# Item.create(name:"Plain Steak", description:"",category_id:10,price:"6.75",price2:"11.49",price3:"")
# Item.create(name:"Cheesesteak", description:"",category_id:10,price:"7.40",price2:"12.49",price3:"")
# Item.create(name:"Cheesesteak Hoagie", description:"Lettuce & Tomato",category_id:10,price:"7.99",price2:"12.99",price3:"")
# Item.create(name:"Pizza Steak", description:"Baked in Oven with Pizza Sauce & Cheese",category_id:10,price:"7.99",price2:"12.99",price3:"")
# Item.create(name:"Special Steak", description:"Cheese, Fried Onions, Green Peppers & Mushrooms",category_id:10,price:"8.25",price2:"13.25",price3:"")
# Item.create(name:"Steak Royal", description:"Fried Onions, Green Peppers, Mushrooms, Pizza Sauce & Cheese",category_id:10,price:"8.25",price2:"13.25",price3:"")
# Item.create(name:"Cheesesteak Platter", description:"With French Fries",category_id:10,price:"9.25",price2:"",price3:"")
# Item.create(name:"Extras", description:"Extra Cheese, Sweet Peppers, Green Peppers, Mushrooms",category_id:10,price:".75",price2:"1.25",price3:"")
# Item.create(name:"Extras", description:"Pepperoni or Bacon",category_id:10,price:"1.25",price2:"1.75",price3:"")
# Item.create(name:"Extras", description:"Extra Mayonnaise",category_id:10,price:".25",price2:".50",price3:"")
# Item.create(name:"Extras", description:"Extra Meat",category_id:10,price:"2.50",price2:"5.00",price3:"")
# Item.create(name:"Extras", description:"Pickles or Peppers on the side",category_id:10,price:".50",price2:".80",price3:"")
Item.create(name:"Plain Chicken Steak", description:"",category_id:11,price:"6.75",price2:"11.49",price3:"")
Item.create(name:"Chicken Cheesesteak", description:"",category_id:11,price:"7.40",price2:"12.49",price3:"")
Item.create(name:"Chicken Cheesesteak Hoagie", description:"Lettuce & Tomatoes",category_id:11,price:"7.99",price2:"12.99",price3:"")
Item.create(name:"Chicken Pizza Steak", description:"",category_id:11,price:"7.99",price2:"12.99",price3:"")
Item.create(name:"Buffalo Chicken Cheesesteak", description:"Blue Cheese, Hot Sauce & American Cheese",category_id:11,price:"7.99",price2:"12.99",price3:"")
Item.create(name:"Grilled Chicken Cheesesteak", description:"",category_id:11,price:"7.40",price2:"12.49",price3:"")
Item.create(name:"Special Chicken Steak", description:"Cheese, Fried Onions, Green Peppers, Pepperoni & Mushrooms",category_id:11,price:"8.25",price2:"13.25",price3:"")
Item.create(name:"Chicken Steak Royal", description:"Fried Onions, Green Peppers, Mushrooms, Pizza Sauce & Cheese",category_id:11,price:"8.25",price2:"13.25",price3:"")
Item.create(name:"Chicken Cheesesteak Platter", description:"With French Fries",category_id:11,price:"9.25",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
