# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Category.create(name:"PIZZA")
# Category.create(name:"GOURMET PIZZAS")
# Category.create(name:"STROMBOLIS")
# Category.create(name:"BURGERS")
# Category.create(name:"HOAGIES")
# Category.create(name:"GRINDERS")
# Category.create(name:"SANDWICHES")
# Category.create(name:"CLUB SANDWICHES")
# Category.create(name:"QUESADILLAS")
# Category.create(name:"STEAKS")
# Category.create(name:"CHICKEN STEAKS")
# Category.create(name:"WRAPS")
# Category.create(name:"BUFFALO WINGS")
# Category.create(name:"BREADED WINGS")
# Category.create(name:"GYROS")
# Category.create(name:"SALADS")
# Category.create(name:"CHICKEN PLATTERS")
# Category.create(name:"SEAFOOD PLATTERS")
# Category.create(name:"PASTA")
# Category.create(name:"SIDE ORDERS")
# Category.create(name:"KIDS MENU")
# Category.create(name:"DESSERTS")
# Category.create(name:"BEVERAGES")

# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"Plain", description:"Sauce & Cheese",category_id:1,price:"5.99",price2:"8.75",price3:"10.25")
# Item.create(name:"White Spices", description:"Olive Oil, Fresh Garlic, Mozzarella, Oregano",category_id:1,price:"5.99",price2:"8.75",price3:"10.25")
# Item.create(name:"White Ricotta", description:"Olive Oil, Fresh Garlic, Oregano, Ricotta & Mozzarella",category_id:1,price:"6.99",price2:"9.99",price3:"11.25")
# Item.create(name:"Upside Down Pizza", description:"Mozzarella & Provolone Cheese & Sauce on Top",category_id:1,price:"6.25",price2:"8.99",price3:"10.49")
# Item.create(name:"Toppings", description:"per topping",category_id:1,price:"1.25",price2:"2.25",price3:"2.40")
# Item.create(name:"1/2 Topping", description:"per topping",category_id:1,price:".70",price2:"1.15",price3:"1.25")
# Item.create(name:"Extra Sauce", description:"",category_id:1,price:".75",price2:"1.50",price3:"2.00")
# Item.create(name:"Buffalo Chicken", description:"Blue Cheese, Buffalo Hot Sauce, Mozzarella & Grilled Chicken",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"BBQ Chicken", description:"BBQ Sauce, Mozzarella, Grilled Chicken",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Greek Pizza", description:"Spinach, Feta, Tomatoes & Olives",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Veggie Supreme", description:"Mushrooms, Onions, Spinach, Green Peppers, Tomatoes, Extra Cheese",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Garden of Earthly Delights", description:"White Pizza with Spinach, Broccoli & Ricotta",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Four Cheese", description:"Mozzarella, Provolone, Colby, Parmesan",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Hawaiian", description:"Ham, Pineapple & Bacon Bits",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Cheese Steak", description:"Topped with our Cheese-Steak Meat",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Meat Lovers", description:"Pepperoni, Sausage, Bacon & Ham",category_id:2,price:"8.99",price2:"12.99",price3:"14.99")
# Item.create(name:"Dimi's Special", description:"Mushrooms, Green Peppers, Pepperoni, Onions, Ground Beef, Sausage, Tomatoes & Extra Cheese",category_id:2,price:"9.99",price2:"13.99",price3:"15.99")
Item.create(name:"Cheese & Sauce", description:"",category_id:3,price:"7.49",price2:"10.99",price3:"")
Item.create(name:"Steak", description:"",category_id:3,price:"9.25",price2:"13.75",price3:"")
Item.create(name:"Pepperoni", description:"Beef or Pork",category_id:3,price:"8.99",price2:"12.99",price3:"")
Item.create(name:"Grilled Chicken", description:"",category_id:3,price:"9.25",price2:"13.75",price3:"")
Item.create(name:"Chicken Steak", description:"",category_id:3,price:"9.25",price2:"13.75",price3:"")
Item.create(name:"Buffalo Chicken", description:"Grilled Chicken w/ Hot Sauce, Mozzarella & Blue Cheese",category_id:3,price:"9.75",price2:"14.25",price3:"")
Item.create(name:"Hot Italian Sausage", description:"",category_id:3,price:"9.25",price2:"13.25",price3:"")
Item.create(name:"Italian Meats", description:"Cappicola, Genoa, Salami, Ham, Green Peppers & Onions",category_id:3,price:"9.25",price2:"13.25",price3:"")
Item.create(name:"Meatball", description:"100% Beef",category_id:3,price:"8.99",price2:"12.99",price3:"")
Item.create(name:"Vegetarian", description:"Mushrooms, Spinach, Green Peppers, Red Onions, Tomatoes & Broccoli",category_id:3,price:"8.99",price2:"12.99",price3:"")
Item.create(name:"Dimi's Special", description:"Steak, Onions, Mushrooms, Pepperoni, Green Peppers",category_id:3,price:"10.75",price2:"14.75",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
