# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Category.create(name:"PIZZA")
# Category.create(name:"GOURMET PIZZAS")
# Category.create(name:"STROMBOLIS")
# Category.create(name:"BURGERS")
# Category.create(name:"HOAGIES")
# Category.create(name:"GRINDERS")
# Category.create(name:"SANDWICHES")
# Category.create(name:"CLUB SANDWICHES")
# Category.create(name:"QUESADILLAS")
# Category.create(name:"STEAKS")
# Category.create(name:"CHICKEN STEAKS")
# Category.create(name:"WRAPS")
# Category.create(name:"BUFFALO WINGS")
# Category.create(name:"BREADED WINGS")
# Category.create(name:"GYROS")
# Category.create(name:"SALADS")
# Category.create(name:"CHICKEN PLATTERS")
# Category.create(name:"SEAFOOD PLATTERS")
# Category.create(name:"PASTA")
# Category.create(name:"SIDE ORDERS")
# Category.create(name:"KIDS MENU")
# Category.create(name:"DESSERTS")
# Category.create(name:"BEVERAGES")

# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"Plain", description:"Sauce & Cheese",category_id:1,price:"5.99",price2:"8.75",price3:"10.25")
# Item.create(name:"White Spices", description:"Olive Oil, Fresh Garlic, Mozzarella, Oregano",category_id:1,price:"5.99",price2:"8.75",price3:"10.25")
# Item.create(name:"White Ricotta", description:"Olive Oil, Fresh Garlic, Oregano, Ricotta & Mozzarella",category_id:1,price:"6.99",price2:"9.99",price3:"11.25")
# Item.create(name:"Upside Down Pizza", description:"Mozzarella & Provolone Cheese & Sauce on Top",category_id:1,price:"6.25",price2:"8.99",price3:"10.49")
Item.create(name:"Toppings", description:"per topping",category_id:1,price:"1.25",price2:"2.25",price3:"2.40")
Item.create(name:"1/2 Topping", description:"per topping",category_id:1,price:".70",price2:"1.15",price3:"1.25")
Item.create(name:"Extra Sauce", description:"",category_id:1,price:".75",price2:"1.50",price3:"2.00")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
# Item.create(name:"", description:"",category_id:,price:"",price2:"",price3:"")
